examples/nextjs/package.json
examples/testbench/package.json

issue with react types, downgraded to fix
was causing wagmi not the be recognised (`Uncaught TypeError: Cannot read property 'mainnet' of undefined`)

fix: downgrade react types to fix nextjs builds

---

packages/connectkit/src/constants/supportedChains.tsx

Arbitrum Rinkeby is deprecated now and marked as read-only. Adding in icon resolution support for the new testnet.

Update supportedChains.tsx with Arbitrum Goerli

---

packages/connectkit/src/components/Common/Chain/index.tsx
packages/connectkit/src/components/Common/ChainSelect/index.tsx

I noticed if the Wagmi configuration has chains not included in the default supported chains list, the "Unknown Chain" logo only appears in the chain select dropdown and not in the ConnectKitModal or ConnectKitButton components. Very easy fix. Thanks for creating such a beautiful project!

Fix unknown chain logo

---

CHANGELOG.md
packages/connectkit/src/components/ConnectKit.tsx
packages/connectkit/src/components/Pages/About/index.tsx
packages/connectkit/src/components/Pages/Onboarding/index.tsx
packages/connectkit/src/localizations/locales/en-US.ts
packages/connectkit/src/localizations/locales/es-ES.ts
packages/connectkit/src/localizations/locales/fr-FR.ts
packages/connectkit/src/localizations/locales/ja-JP.ts
packages/connectkit/src/localizations/locales/zh-CN.ts

**Fixes: https://github.com/family/connectkit/issues/75**
- Removes [sunset ethhub.io](https://twitter.com/econoar/status/1600932091398529024) link (https://docs.ethhub.io/using-ethereum/wallets/intro-to-ethereum-wallets) and replaces with ethereum.org's wallet onboarding page (https://ethereum.org/en/wallets/).
- Gives developers the option to replace external links within the `ConnectKitProvider` options under `options.walletOnboardingUrl` and `options.ethereumOnboardingUrl`.

fix: dead links

---

CHANGELOG.md
examples/testbench/src/TestbenchProvider.tsx
examples/testbench/src/pages/index.tsx
packages/connectkit/src/components/ConnectKit.tsx
packages/connectkit/src/components/ConnectModal/ConnectWithInjector/index.tsx
packages/connectkit/src/components/Pages/MobileConnectors/index.tsx
packages/connectkit/src/defaultClient.ts
packages/connectkit/src/hooks/useConnect.tsx
packages/connectkit/src/index.ts

Addresses: https://github.com/family/connectkit/issues/44
- Changes the way configured chains are handled around ConnectKit
- Gives developers option to turn off a targeted `chainId` during connection (will connect to the currently connected network instead)
- Gives access to the configured list of chains for developers to use before a wallet is connected
- - [wagmi's useNetwork](https://wagmi.sh/react/hooks/useNetwork) hook does not expose the available chains until after a wallet has been connected. This update now gives developers access to this list if they use the `defaultClient` helper

update: better configured chains

---

CHANGELOG.md
examples/cra/package.json
examples/nextjs/package.json
examples/testbench/package.json
examples/testbench/src/pages/_app.tsx
examples/testbench/src/styles/globals.css
examples/vite/package.json
package.json
packages/connectkit/package.json
packages/connectkit/src/components/ConnectModal/ConnectWithQRCode.tsx
packages/connectkit/src/components/Pages/Connectors/index.tsx
packages/connectkit/src/defaultClient.ts
packages/connectkit/src/wallets/connectors/argent.tsx
packages/connectkit/src/wallets/connectors/frontier.tsx
packages/connectkit/src/wallets/connectors/gnosisSafe.tsx
packages/connectkit/src/wallets/connectors/imToken.tsx
packages/connectkit/src/wallets/connectors/ledger.tsx
packages/connectkit/src/wallets/connectors/metaMask.tsx
packages/connectkit/src/wallets/connectors/onto.tsx
packages/connectkit/src/wallets/connectors/rainbow.tsx
packages/connectkit/src/wallets/connectors/slope.tsx
packages/connectkit/src/wallets/connectors/steak.tsx
packages/connectkit/src/wallets/connectors/trust.tsx
packages/connectkit/src/wallets/connectors/unstoppable.tsx
packages/connectkit/src/wallets/connectors/walletConnect.tsx
packages/connectkit/src/wallets/connectors/zerion.tsx
packages/connectkit/src/wallets/wallet.ts
packages/cra-template/template.json
yarn.lock

Upgrade the `wagmi` peer dependency to `0.10.x`, which requires changes in the connector configurations
This does not include full support for WalletConnect 2.0
**release notes for wagmi 0.10.0**
https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.10.0

update: wagmi 0.10.x

---

packages/connectkit/package.json

this lets any version of wagmi's minor release version 10 be usable with connectkit

change: peer dependency wagmi to 0.10.x

---

CHANGELOG.md
packages/connectkit/package.json
packages/connectkit/rollup.config.dev.js
packages/connectkit/rollup.config.prod.js
packages/cra-template/template.json

Terser minifying was only set up on the prod rollup config, this PR syncs the dev and prod configs more closely so we can avoid future app errors that aren't visible during the build process.
Terser doesn't seem to work with Next 13's default [`swcMinify: true`](https://nextjs.org/docs/advanced-features/compiler#minification) config setting, and they recommend setting this config to `false` if Terser is needed, but this is not something we should be requesting developers to change in their apps, so we need to remove Terser minifying on prod.
Fixes https://github.com/family/connectkit/issues/89

fix: sync dev/prod rollup configs (remove terser)

---

packages/connectkit/src/defaultClient.ts
packages/connectkit/src/wallets/connectors/metaMask.tsx

I don't understand why [`shimChainChangedDisconnect `](https://wagmi.sh/react/connectors/metaMask#shimchainchangeddisconnect) is disabled. This flag prevents a bug in metamask where switching network will result in disconnecting. It should be enabled.
This metamask bug only happens when switching from a default network to a custom network. Please refer to [this](https://github.com/wagmi-dev/wagmi/issues/1239#issuecomment-1304660937).

fix: metamask disconnect when switching network

---

CHANGELOG.md
examples/testbench/src/pages/index.tsx
packages/connectkit/src/components/ConnectButton/index.tsx

This PR adds the currently connected chain to the exports for the `ConnectKitButton.Custom` component.

add: chain to custom connect button

---

packages/connectkit/src/components/Standard/SIWE/SIWEProvider.tsx

fixes https://github.com/family/connectkit/issues/111

fix: convert both addresses to same format before comparing in SIWE config `signOutOnAccountChange` case

---

packages/connectkit/src/index.ts

React apps that include multiple renderers (`react-dom` + `react-three-fiber` in my case) don't automatically share context, so it ends up being necessary to reference the context manually to wire them together with [something like this](https://github.com/pmndrs/drei#usecontextbridge).
This PR just adds the Context to the package's exports.

adds Context export

---

examples/testbench/src/pages/index.tsx
packages/connectkit/src/components/Common/Modal/index.tsx
packages/connectkit/src/components/ConnectButton/index.tsx
packages/connectkit/src/components/ConnectKit.tsx
packages/connectkit/src/components/Pages/SignInWithEthereum/index.tsx
packages/connectkit/src/components/Standard/SIWE/index.tsx
packages/connectkit/src/hooks/useModal.ts
packages/connectkit/src/index.ts
packages/connectkit/src/siwe/useSIWE.ts

Adds functions to `useModal` hook to open direct to pages
Will fallback to default routes when opening to a route that is not allowed (e.g when no wallet is connected you can't navigate to the profile page)
* https://github.com/family/connectkit/discussions/146

adds: options to choose which page to navigate to when opening modal

---

packages/connectkit-next-siwe/src/configureSIWE.tsx
packages/connectkit/src/index.ts

gm sers!
We're big fans of ConnectKit here at Metadrop, but we've ran into a few limitations which this PR is addressing:
1. We want to be able to perform server-side actions as part of the SIWE endpoints (similar to how [Auth0](https://github.com/auth0/nextjs-auth0) does it in their `handleAuth` handler), instead of requiring separate API calls post-SIWE for things like user management
2. It's very useful to have access to the modal context for things like navigation (i.e. presenting the sign in state immediately if wallet is already connected, instead of requiring the user to click "Connect" again to get to the SIWE screen)
Plz approve and merge thank you 🙏🏻

SIWE route configurations

---

packages/connectkit/src/assets/logos.tsx
packages/connectkit/src/utils/index.ts
packages/connectkit/src/wallets/connectors/frame.tsx
packages/connectkit/src/wallets/index.ts
packages/connectkit/src/wallets/useDefaultWallets.tsx

Adding injected support for [Frame](https://frame.sh).

add Frame support

---

packages/connectkit/src/hooks/useWalletConnectModal.tsx

updates web3modal z-index variable name, and keeps previous versions for those who are on older versions of wagmi
opting to not use the [walletconnect `themeVariables`](https://docs.walletconnect.com/2.0/web/walletConnectModal/modal/options#themevariables-optional) to set the z-index because if wagmi version isn't correct this could throw errors. we will move to this at a later date.

fix: w3m overrides

---

packages/connectkit/src/hooks/connectors/useInjectedWallet.tsx

adds check for when trying to get `name` when injected connector isn't in the configs.
fixes: #294

fix: check if injected connector exists

---

packages/connectkit/src/components/Common/ChainSelectList/index.tsx
packages/connectkit/src/components/Common/Modal/index.tsx
packages/connectkit/src/components/ConnectKit.tsx

* adds resize trigger
* hides "approve in wallet" text on secondary switchnetwork view
* shows error when `switchNetwork` throws error code `4902` instead of on any error
fixes: #277 #78

Fix: UI hidden on rejected network change

---

packages/connectkit/src/utils/wallets.ts
packages/connectkit/src/wallets/connectors/zerion.tsx

- Fixes support for Zerion extension by following the `isInstalled` pattern used by other wallets
**Before**
**After**

add zerion extension support

---

packages/connectkit/src/components/Common/Modal/index.tsx

I don't know if you'd like a demonstration of the tweak, but it's a super minimal bugfix. I mentioned this in #304 and just remembered about it, sorry for the delay.

Fix: Hide siwe tooltip when hiteTooltips is enabled

---

CHANGELOG.md
examples/nextjs-app/config.ts
examples/nextjs-siwe/src/pages/_app.tsx
examples/testbench/src/components/Web3Provider.tsx
examples/testbench/src/pages/chains.tsx
examples/testbench/src/pages/index.tsx
packages/connectkit/package.json
packages/connectkit/src/components/BalanceButton/index.tsx
packages/connectkit/src/components/Common/Chain/index.tsx
packages/connectkit/src/components/Common/ChainSelect/index.tsx
packages/connectkit/src/components/ConnectButton/index.tsx
packages/connectkit/src/components/ConnectKit.tsx
packages/connectkit/src/components/ConnectModal/demo.tsx
packages/connectkit/src/components/ConnectModal/index.tsx
packages/connectkit/src/components/Pages/MobileConnectors/index.tsx
packages/connectkit/src/components/Pages/SwitchNetworks/index.tsx
packages/connectkit/src/components/contexts/web3/index.tsx
packages/connectkit/src/hooks/useChainIsSupported.ts
packages/connectkit/src/hooks/useModal.ts
packages/connectkit/src/index.ts
packages/cra-template/template.json
packages/cra-template/template/src/index.tsx

fix: unsupported chain flagging

---

packages/connectkit/src/hooks/useConnect.tsx
packages/connectkit/src/hooks/useLastConnector.ts

remove our localstorage solution and opting for wagmi's storage as this stores the same information

update: use wagmi storage instead of connectkit storage

---

packages/connectkit/src/components/BalanceButton/index.tsx
packages/connectkit/src/hooks/useChainIsSupported.ts

- When showBalance=true on ConnectKitButton and when chain is supported, balance is not properly displayed.
- Bad loading on Chain component logo at initialization.
- Invalid useConfig hook order inside useChainIsSupported hook.
- Rename "unsupported" to "isChainSupported" to improve consistency with other parts of the codebase.
- Inverse boolean condition to fix the bug on balance.
- Proper initial logo loading by adding id prop to Chain component.
- Move useConfig hook at the top of useChainIsSupported hook to avoid "change in the order of Hooks" on early return.

Fix isChainSupported in BalanceButton

---

packages/connectkit/src/siwe/SIWEProvider.tsx

It appears that in @tanstack/react-query v5 and up the query will not be fetched on mount if `initialData` is anything other than `undefined`. This means that the `ckSiweNonce` and `ckSiweSession` queries don't fire for the first time until their respective intervals have elapsed.
This commit removes the `initialData` for both of these queries in order to restore previous functionality.
Versions used to reproduce issue:
`"@tanstack/react-query": "5.18.1"` & `"connectkit": "1.7.1"`

Remove initialData in nonce and session

---

packages/connectkit/src/assets/logos.tsx
packages/connectkit/src/hooks/useConnectors.ts
packages/connectkit/src/hooks/useWalletConnectModal.tsx
packages/connectkit/src/utils/index.ts

fixes: https://github.com/family/connectkit/issues/359

fix: missing projectId in "More" mobile button + remove wc legacy 

---

packages/connectkit/src/components/Common/Avatar/index.tsx
packages/connectkit/src/components/ConnectButton/index.tsx
packages/connectkit/src/components/Pages/Profile/index.tsx
packages/connectkit/src/hooks/useEnsFallbackConfig.ts

- [Check issue 350](https://github.com/family/connectkit/issues/350) reported by @SonOfMosiah
- Add useEnsFallbackConfig hook to easily guarantee mainnet access to all ENS-related hooks, regardless of the chains supported by the dapp.

Fix ENS resolution if mainnet not supported

---

packages/connectkit/src/index.ts
packages/connectkit/src/siwe/SIWEProvider.tsx
packages/connectkit/src/siwe/index.ts

In order to refetch the SIWE session on account change, I need to imperatively trigger a refetch of the `session` query in [SIWEProvider.tsx](https://github.com/family/connectkit/blob/main/packages/connectkit/src/siwe/SIWEProvider.tsx#L54-L58).
This can be achieved without a const by simply targetting the query key of string "ckSiweSession" - however it is brittle and susceptible to breaking changes.
Exporting these query keys as constants allows package consumers to refetch/manipulate the queries as necessary.

chore(query-keys): Export `SIWEProvider`'s two query keys, allowing package consumers to invalidate queries

---

examples/testbench/src/pages/index.tsx
packages/connectkit/src/localizations/index.tsx
packages/connectkit/src/localizations/locales/ca-AD.ts

This commit introduces support for the Catalan language as spoken in Andorra and Catalonia (ca_AD).
Changes include:
- Added new language files for ca_AD compatibility.
With these changes, users can now select ca_AD from the language options.

Add ca_AD Language Support

---

packages/connectkit/src/components/Common/ConnectorList/index.tsx
packages/connectkit/src/wallets/walletConfigs.tsx

Fixes:
- #379 
- LedgerLive desktop wallet support

fix: deeplinks for desktop apps

---

packages/connectkit/src/assets/chains.tsx
packages/connectkit/src/constants/chainConfigs.tsx

add: zora + base logos

---

.github/workflows/dependency-review.yml

The dependency review action scans your pull requests for dependency changes and raises an error if any new dependencies have known vulnerabilities. Once installed, if the workflow run is marked as required, pull requests introducing known vulnerable packages will be blocked from merging.

feat: Add dependency review
